objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    portainer_config:
      description: Manage Portainer environment configs
      name: portainer_config
      namespace: ''
      version_added: 1.0.0
    portainer_environment:
      description: Manage Portainer environments
      name: portainer_environment
      namespace: ''
      version_added: 1.0.0
    portainer_environment_info:
      description: Gets Portainer environment info
      name: portainer_environment_info
      namespace: ''
      version_added: 1.0.0
    portainer_group:
      description: Manage Portainer environment groups
      name: portainer_group
      namespace: ''
      version_added: 1.0.0
    portainer_network:
      description: Manage Portainer environment networks
      name: portainer_network
      namespace: ''
      version_added: 1.0.0
    portainer_secret:
      description: Manage Portainer environment secrets
      name: portainer_secret
      namespace: ''
      version_added: 1.0.0
    portainer_stack:
      description: Manage Portainer environment stacks
      name: portainer_stack
      namespace: ''
      version_added: 1.0.0
    portainer_tag:
      description: Manage Portainer tags
      name: portainer_tag
      namespace: ''
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.0.3
